language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install nose coverage flake8
  - python setup.py develop
script: 
  - flake8 setup.py src
  - nosetests --with-coverage --cover-package=calmjs --with-doctest --doctest-options=+ELLIPSIS
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - master
