environment:
  nodejs_version: "4.5"
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - "%PYTHON%\\python.exe -m pip install coverage"
  - "%PYTHON%\\python.exe setup.py install"

test_script:
  # piping empty echo to disable the tty test which is reported as
  # working but actually non-working on appveyor.
  - echo | coverage run setup.py test
  - coverage report -m

artifacts:
  - path: dist\*

build: off
