environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "4.6"
    - PYTHON: "C:\\Python33"
      nodejs_version: "4.6"
    - PYTHON: "C:\\Python34"
      nodejs_version: "6.9"
    - PYTHON: "C:\\Python35"
      nodejs_version: "6.9"
    - PYTHON: "C:\\Python36"
      nodejs_version: "7.4"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - "%PYTHON%\\python.exe -m pip install coverage"
  - "%PYTHON%\\python.exe setup.py install"

test_script:
  # piping empty echo to disable the tty test which is reported as
  # working but actually non-working on appveyor.
  - echo | coverage run setup.py test
  - coverage report -m

artifacts:
  - path: dist\*

build: off
